#include <iostream>
#include <string>
#include <cassert>

class Solution {
public:
    //You are given two strings s and t.
    //String t is generated by random shuffling string s and then add one more letter at a random position.
    //Return the letter that was added to t.
    char findTheDifference(std::string s, std::string t)
    {
        if (s.empty())
        {
            return t[0];
        }

        size_t size = s.size();

        for (int i = 0; i < size; ++i)
        {
            size_t pos = s.find(t[i]);
            if (pos == std::string::npos)
            {
                return t[i];
            }
            s.erase(s.begin() + pos);
        }
        return t[size];
    }
};

void Test()
{
    Solution su;
    {
        std::string s = "abcd", t = "abcde";
        assert(su.findTheDifference(s, t) == 'e');
    }
    {
        std::string s = "", t = "y";
        assert(su.findTheDifference(s, t) == 'y');
    }
    {
        std::string s = "abcd", t = "eabcd";
        assert(su.findTheDifference(s, t) == 'e');
    }
    {
        std::string s = "abcd", t = "acbad";
        assert(su.findTheDifference(s, t) == 'a');
    }
    std::cout << "DONE!" << std::endl;
}

int main()
{
    Test();
}